# Generated by Django 3.2 on 2021-05-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
