# Generated by Django 3.2 on 2021-05-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='phone',
            field=models.CharField(default='', max_length=111),
        ),
    ]
